export const data = [
  {
    key: "blue1.jpg",
    url: "src/assets/blue1.jpg",
    isRed: false,
    isYellow: false,
    isBlue: true,
    altText: "Blue night sky with full moon shining behind tree branches",
  },
  {
    key: "blue2.jpg",
    url: "src/assets/blue2.jpg",
    isRed: false,
    isYellow: false,
    isBlue: true,
    altText: "All blue photo of blue rose with mildew",
  },
  {
    key: "blue3.jpg",
    url: "src/assets/blue3.jpg",
    isRed: false,
    isYellow: false,
    isBlue: true,
    altText: "Blue night sky with lightning and castle in the far background",
  },
  {
    key: "green1.jpg",
    url: "src/assets/green1.jpg",
    isRed: false,
    isYellow: true,
    isBlue: true,
    altText: "Aerial view of a forest of evergreen trees",
  },
  {
    key: "green2.jpg",
    url: "src/assets/green2.jpg",
    isRed: false,
    isYellow: true,
    isBlue: true,
    altText: "A bunch of green apples with one split open on top",
  },
  {
    key: "green3.jpg",
    url: "src/assets/green3.jpg",
    isRed: false,
    isYellow: true,
    isBlue: true,
    altText: "Overhead view of a dark green plant",
  },
  {
    key: "orange1.jpg",
    url: "src/assets/orange1.jpg",
    isRed: true,
    isYellow: true,
    isBlue: false,
    altText: "A bunch of oranges with one split open on top",
  },
  {
    key: "orange2.jpg",
    url: "src/assets/orange2.jpg",
    isRed: true,
    isYellow: true,
    isBlue: false,
    altText: "A table full of orange colored fruits, vegetables, and spices",
  },
  {
    key: "orange3.jpg",
    url: "src/assets/orange3.jpg",
    isRed: true,
    isYellow: true,
    isBlue: false,
    altText:
      "Horizontally aligned, long orange feathers taking up the whole image",
  },
  {
    key: "red1.jpg",
    url: "src/assets/red1.jpg",
    isRed: true,
    isYellow: false,
    isBlue: false,
    altText: "A bunch of shiny red raspberries",
  },
  {
    key: "red2.jpg",
    url: "src/assets/red2.jpg",
    isRed: true,
    isYellow: false,
    isBlue: false,
    altText: "Overhead view of several red carnation flowers",
  },
  {
    key: "red3.jpg",
    url: "src/assets/red3.jpg",
    isRed: true,
    isYellow: false,
    isBlue: false,
    altText: "A close up on a bunch of perfectly ripe strawberries",
  },
  {
    key: "yellow1.jpg",
    url: "src/assets/yellow1.jpg",
    isRed: false,
    isYellow: true,
    isBlue: false,
    altText: "An underneath view of a tree whose leaves have turned yellow",
  },
  {
    key: "yellow2.jpg",
    url: "src/assets/yellow2.jpg",
    isRed: false,
    isYellow: true,
    isBlue: false,
    altText: "A close up of a yellow rose",
  },
  {
    key: "yellow3.jpg",
    url: "src/assets/yellow3.jpg",
    isRed: false,
    isYellow: true,
    isBlue: false,
    altText: "A close up of Spongebob Squarepants' face looking perplexed",
  },
  {
    key: "purple1.avif",
    url: "src/assets/purple1.avif",
    isRed: true,
    isYellow: false,
    isBlue: true,
    altText:
      "An all purple photo of the upper half of a cat's face. The cat looks purple and their eyes are bluish",
  },
  {
    key: "purple2.jpg",
    url: "src/assets/purple2.jpg",
    isRed: true,
    isYellow: false,
    isBlue: true,
    altText:
      "A close up of a bunch of purple potatoes with the first one cut open.",
  },
  {
    key: "purple3.avif",
    url: "src/assets/purple3.avif",
    isRed: true,
    isYellow: false,
    isBlue: true,
    altText: "A collage of 16 photos all tinted purple",
  },
];

export const imgLinks = data.map(
  (img) => `https://colorreel.mannyrodriguez3.repl.co/img/${img.key}`
);

export default data;
